// <auto-generated />
using ExploringSelfSovereignIdentityAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExploringSelfSovereignIdentityAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ExploringSelfSovereignIdentityAPI.Models.Default.DefaultSessionModel", b =>
                {
                    b.Property<short>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("SessionId"), 1L, 1);

                    b.Property<string>("_identityIdentityName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("otp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessionId");

                    b.HasIndex("_identityIdentityName");

                    b.ToTable("defaultSessionModel", (string)null);
                });

            modelBuilder.Entity("ExploringSelfSovereignIdentityAPI.Models.DefaultIdentity.DefaultIdentityModel", b =>
                {
                    b.Property<string>("IdentityName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HolderSignature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdentityName");

                    b.ToTable("DefaultIdentityModel", (string)null);
                });

            modelBuilder.Entity("ExploringSelfSovereignIdentityAPI.Models.Default.DefaultSessionModel", b =>
                {
                    b.HasOne("ExploringSelfSovereignIdentityAPI.Models.DefaultIdentity.DefaultIdentityModel", "_identity")
                        .WithMany()
                        .HasForeignKey("_identityIdentityName");

                    b.Navigation("_identity");
                });
#pragma warning restore 612, 618
        }
    }
}
