// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconBiometric: typeof import('./src/components/icons/IconBiometric.vue')['default']
    IconButton: typeof import('./src/components/buttons/IconButton.vue')['default']
    IconButtonNoBG: typeof import('./src/components/buttons/IconButtonNoBG.vue')['default']
    IconGoogle: typeof import('./src/components/icons/IconGoogle.vue')['default']
    IconHeading: typeof import('./src/components/icons/IconHeading.vue')['default']
    ImageCard: typeof import('./src/components/cards/ImageCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
