// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackNav: typeof import('./src/components/Nav/BackNav.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElRow: typeof import('element-plus/es')['ElRow']
    IconAvatar: typeof import('./src/components/icons/IconAvatar.vue')['default']
    IconBiometric: typeof import('./src/components/icons/IconBiometric.vue')['default']
    IconButton: typeof import('./src/components/Buttons/IconButton.vue')['default']
    IconButtonNoBG: typeof import('./src/components/Buttons/IconButtonNoBG.vue')['default']
    IconFile: typeof import('./src/components/icons/IconFile.vue')['default']
    IconGoogle: typeof import('./src/components/icons/IconGoogle.vue')['default']
    IconHeading: typeof import('./src/components/icons/IconHeading.vue')['default']
    IconHome: typeof import('./src/components/icons/IconHome.vue')['default']
    IconMenu: typeof import('./src/components/icons/IconMenu.vue')['default']
    IconPast: typeof import('./src/components/icons/IconPast.vue')['default']
    IconPending: typeof import('./src/components/icons/IconPending.vue')['default']
    ImageCard: typeof import('./src/components/cards/ImageCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
