name: ExploringSelfSovereignIdentity

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  API:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./ExploringSelfSovereignIdentityAPI
      run: dotnet restore
    - name: BuildAPI
      working-directory: ./ExploringSelfSovereignIdentityAPI
      run: dotnet build --no-restore
    - name: TestAPIUnit
      working-directory: ./ExploringSelfSovereignIdentityAPIUnitTests
      run: dotnet test
    - name: TestAPIIntegration
      working-directory: ./ExploringSelfSovereignIdentityIntegrationAPI.Tests
      run: dotnet test
  
  Frontend:
  
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Installing project dependencies
        working-directory: ./SSIVueJsClient
        run: npm install
      - name: Building the project
        working-directory: ./SSIVueJsClient
        run: npm run build
      - name: Running Unit Tests
        working-directory: ./SSIVueJsClient
        run: npm run test:unit
      - name: Running Server
        working-directory: ./SSIVueJsClient
        run: npm run & wait-on http://localhost:3000
      - name: Running Integration Tests
        working-directory: ./SSIVueJsClient
        run: cypress run
  
  SmartContract:
  
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Installing Truffle
        working-directory: ./LocalBlockchain
        run: npm install truffle
      - name: Installing All
        working-directory: ./LocalBlockchain
        run: npm install
        
  
  CodeCov-API:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v2
      with:
       token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
       files: ./ExploringSelfSovereignIdentityAPIUnitTests/coverage.opencover.xml # optional
       flags: unittests # optional
       name: codecov-umbrella # optional
       fail_ci_if_error: true # optional (default = false)
       verbose: true # optional (default = false)
