name: ExploringSelfSovereignIdentity

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  API:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./ExploringSelfSovereignIdentityAPI
      run: dotnet restore
    - name: BuildAPI
      working-directory: ./ExploringSelfSovereignIdentityAPI
      run: dotnet build --no-restore
    - name: TestAPI
      working-directory: ./ExploringSelfSovereignIdentityAPIUnitTests
      run: dotnet test
      
  Client:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.15.x
    
    - name: Cache node modules
      id: cache-nodemodules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # caching node_modules
        path: node_modules # 👈 path for node_modules folder
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        # 👆 name of the chache key includes package-lock.json
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
  
    - name: npm dependencies
      run: npm install
      
    - name: BuildClient
      working-directory: ./ExploringSelfSovereignIdentityClient
      run: npm build -- --prod
      
    - name: Lint
      run: npm run Lint
      
    - name: TestClient
      working-directory: ./ExploringSelfSovereignIdentityClient
      run: npm run test -- --prod
