name: ExploringSelfSovereignIdentity

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  API:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./ExploringSelfSovereignIdentityAPI
      run: dotnet restore
    - name: BuildAPI
      working-directory: ./ExploringSelfSovereignIdentityAPI
      run: dotnet build --no-restore
    - name: TestAPI
      working-directory: ./ExploringSelfSovereignIdentityAPIUnitTests
      run: dotnet test
      
  Client:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup NPM
      uses: actions/setup-npm@v2
      with:
        npm-version: 6.14.x

    - name: BuildAPI
      working-directory: ./ExploringSelfSovereignIdentityClient
      run: npm build
      
    - name: TestAPI
      working-directory: ./ExploringSelfSovereignIdentityClient
      run: npm test
